### ISSUE TITLE
The HTML exporter results doesn't look like the capture used on "readme"

### ISSUE THREAD

**Issue by zakiournani** [powerapi-ng/joulehunter#26]
So I ve tried to run joulehunter with an HTML exporter (because the depth was high to use the CLI version, joulehunter crashed)
The problem with the HTML version is that the result is pretty empty
What is mainly missing is the 'J' unit next to the consumption numbers, the consumption percenteges and the whole header with data on duration , package, etc. 

![Capture](https://user-images.githubusercontent.com/8063020/199552127-6844bfef-2305-4a14-8c55-2f146a2c7e36.PNG)

**Comment by chakib-belgaid** [comment]
fixed in version 1.0.2
